config/routes.rb
Rails.application.routes.draw do
  
  get '/login', to: 'users#login_form'
  post '/login', to: 'users#login'
  post '/logout', to: 'users#logout'
  
  get '/users/:id/likes', to: 'users#likes'
  get '/users/:id/actionplan', to: 'users#actionplan'
  
  resources :users do
    resources :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  root 'static_pages#home'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :user_id, {presence: true}
  validates :post_id, {presence: true}
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user
  before_action :post_params
  
  def create
    @like = @current_user.likes.new(post_id: @post.id)
    @like.save
  end
  
  def destroy
    @like = Like.find_by(user_id: @current_user.id,
                          post_id: params[:post_id])
    @like.destroy
  end
  
  private
  def post_params
    @post = Post.find(params[:post_id])
  end
end

app/views/likes/_like.html.erb
<% if @current_user.already_liked?(@post) %>
      
        <%= link_to(post_like_path(post_id: @post.id, id: @post.likes[0].id), method: :delete, remote: true) do %>
        <span class="fa fa-heart like-btn-unlike"></span>
        <% end %>
        
      <% else %>
      
        <%= link_to(post_likes_path(@post.id), method: :post, remote: true) do %>
        <span class="fa fa-heart like-btn"></span>
        <% end %>
        
<% end %>
      
      <%= @post.likes.count %>

app/views/likes/create.js.erb
// #like_buttonの部分のHTMLだけ、renderで部分的に更新
$('.like_button').html("<%= j(render partial: 'likes/like', locals: { post: @post } ) %>");

app/views/likes/destroy.js.erb
$('.like_button').html("<%= j(render partial: 'likes/like', locals: { post: @post }) %>");