config/routes.rb
Rails.application.routes.draw do
  
  get '/login', to: 'users#login_form'
  post '/login', to: 'users#login'
  post '/logout', to: 'users#logout'
  
  get '/users/:id/likes', to: 'users#likes'
  get '/users/:id/actionplan', to: 'users#actionplan'
  
  resources :users do
    resources :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  root 'static_pages#home'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :email, presence: true, uniqueness: true
  
  mount_uploader :image_name, ImageNameUploader
 
  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :comments
  
  # ========自分がフォローしているユーザーとの関連 =========== #
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので、親はfollowing_id(フォローする側)
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  #中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「following」と定義
  has_many :followings, through: :active_relationships, source: :follower
  # ========================================================== #
  
   # ========自分がフォローされるユーザーとの関連 =========== #
  #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので、親はfollower_id(フォローされる側)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  #中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relationships, source: :following
  # ========================================================== #
  
  def followed_by?(user)
    #ユーザーがfollow済みかどうかを判定
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end

  
  def posts
    return Post.where(user_id: self.id).order(created_at: :desc)
  end
  
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:index, :show, :edit, :update]}
  before_action :forbid_login_user, {only: [:new, :create, :login_form, :login]}
  before_action :ensure_correct_user, {only: [:edit, :update]}
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find_by(id: params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to("/users/#{@user.id}")
    else
      render("/users/new")
    end
  end
  
  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    redirect_to "/"
    flash[:notice] = "ユーザーを削除しました。"
  end
  
  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to("/users/#{@user.id}")
    else
      render("users/#{@user.id}/edit")
    end
  end

  
  def login_form
  end
  
  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to("/users/#{@user.id}")
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]
      @password = params[:password]
      render("users/login_form")
    end
  end
  
  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/login")
  end
  
  def likes
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id).order(created_at: :desc).includes(:user)
  end
  
  def actionplan
     @user = User.find_by(id: params[:id])
  end
  
  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice] = "権限がありません"
      redirect_to("/posts")
    end
  end
  
  def follows
    @user = User.find(params[:id])
    @users = @user.followings
  end
  
  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end
    
  
  private
  def user_params
    params.permit(:name, :email, :password, :image_name)
  end
end
  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/actionplan.html.erb
<div class="main user-show">
  <div class="container">
     <div class="user">
      <h2><%= @user.name %></h2>
     <% if @user.image_name? %>
      <%= image_tag @user.image_name.url %>
     <% else %>
      <%= image_tag "/user_images/default_user.jpg", class: 'user_sized' %>
     <% end %>
      <p><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
      <%= link_to("編集",edit_user_path) %>
      <%= link_to("削除", user_path, {method: "delete"}) %>
      <% end %>
    </div>
    
    <div class="figure-sum-posts">
      <p>投稿数合計<%= @user.posts.count %>冊</p>
    </div>
   
    
    <ul class="user-tabs">
      <li><%= link_to("投稿","/users/#{@user.id}") %></li>
      <li><%= link_to("いいね！","/users/#{@user.id}/likes") %></li> 
      <li class="active"><%= link_to("私のアクションプラン","/users/#{@user.id}/actionplan") %></li>
      <li><%= link_to "フォロー", follows_user_path(@user.id) %></li>
      <li><%= link_to "フォロワー", followers_user_path(@user.id) %></li>
    </ul>
   
      
    <% @user.posts.each do |post| %>
    <div class="posts-index-item">
      <div class="post-right">
        <div class="post-user-name">
          <%= link_to(post.user.name, "/users/#{post.user.id}") %>
        </div>
        <%= link_to(post.content,"/posts/#{post.id}") %>
        <br>
        <%= link_to(post.actionplan,"/posts/#{post.id}") %>
      </div>
    </div>
    <% end %>
    
  </div>
</div>

app/views/users/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <div class="form-heading">アカウント編集</div>
    <div class="form users-form">
      <div class="form-body">
        <!-- エラーメッセージを表示 -->
        <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
        
        <!-- フォームの送信先を指定 -->
        <%= form_for(@user, url: user_path(@user)) do |f| %>
          <%= f.label :ユーザー名 %><br>
          <%= f.text_field :name, class: 'form-control' %><br>
          <%= f.label :ユーザー画像 %><br>
          <%= f.file_field :image_name %><br>
          <%= f.label :メールアドレス %><br>
          <%= f.text_field :email, class: 'form-control' %><br>
          <%= f.submit '更新する', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <h2><%= @user.name %></h2>
      <% if @user.image_name? %>
          <%= image_tag @user.image_name.url %>
        <% else %>
          <%= image_tag "/user_images/default_user.jpg", class: 'user_sized' %>
        <% end %>
      <p><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
      <%= link_to("編集","/users/#{@user.id}/edit") %>
      <%= link_to("削除","/users/#{@user.id}", {method: "delete"}) %>
      <% end %>
    </div>
    
    <div class="figure-sum-posts">
      <p>投稿数合計<%= @user.posts.count %>冊</p>
    </div>
   
    
    <ul class="user-tabs">
      <li><%= link_to("投稿","/users/#{@user.id}") %></li>
      <li><%= link_to("いいね！","/users/#{@user.id}/likes") %></li> 
      <li><%= link_to("私のアクションプラン","/users/#{@user.id}/actionplan") %></li>
      <li><%= link_to "フォロー", follows_user_path(@user.id) %></li>
      <li class="active"><%= link_to "フォロワー", followers_user_path(@user.id) %></li>
    </ul>
   
    <% @users.each do |user| %>
  <hr>
  <p><span>name: </span><%= link_to user.name, user_path(user.id) %></p>
    <% if @current_user != user %>
        <% if user.followed_by?(@current_user) %>
            <p><%=link_to "フォロー済み", user_relationship_path(user_id: user, id: user), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>
<% end %>  
    
    
  </div>
</div>

app/views/users/follows.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
        <h2><%= @user.name %></h2>
      <% if @user.image_name? %>
          <%= image_tag @user.image_name.url %>
        <% else %>
          <%= image_tag "/user_images/default_user.jpg", class: 'user_sized' %>
        <% end %>
      <p><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
      <%= link_to("編集","/users/#{@user.id}/edit") %>
      <%= link_to("削除","/users/#{@user.id}", {method: "delete"}) %>
      <% end %>
    </div>
    
    <div class="figure-sum-posts">
      <p>投稿数合計<%= @user.posts.count %>冊</p>
    </div>
   
    
    <ul class="user-tabs">
      <li><%= link_to("投稿","/users/#{@user.id}") %></li>
      <li><%= link_to("いいね！","/users/#{@user.id}/likes") %></li> 
      <li><%= link_to("私のアクションプラン","/users/#{@user.id}/actionplan") %></li>
      <li class="active"><%= link_to "フォロー", follows_user_path(@user.id) %></li>
      <li><%= link_to "フォロワー", followers_user_path(@user.id) %></li>
    </ul>
   
      
  <% @users.each do |user| %>
  <hr>
  <p><span>name: </span><%= link_to user.name, user_path(user.id) %></p>
    <% if @current_user != user %>
        <% if user.followed_by?(@current_user) %>
            <p><%=link_to "フォロー済み", user_relationship_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>
  <% end %>
    
  </div>
</div>

app/views/users/index.html.erb
<div class="main users-index">
  <div class="container">
    <h1 class="users-heading">ユーザー一覧</h1>
    <% @users.each do |user| %>
     <div class="users-index-item">
       <div class="user-left">
         <% if user.image_name? %>
          <%= image_tag user.image_name.url %>
         <% else %>
          <%= image_tag "/user_images/default_user.jpg", class: 'user_sized' %>
         <% end %>
       </div>
       <div class="user-right">
         <%= link_to(user.name, "/users/#{user.id}") %>
       </div>
       <!-- フォロー機能 -->
       <div class="follow-button">
       <% if @current_user != user %>
       <% if user.followed_by?(@current_user) %>
         <p><%= link_to "フォロー済み", user_relationship_path(user_id: user, id: user),class: 'btn btn-primary', method: :delete %></p>
       <% else %>
         <p><%= link_to "フォローする", user_relationships_path(user.id),class: 'btn btn-primary', method: :post %></p>
       <% end %>
       <% end %>
       </div>
       <!-- ここまで -->
     </div>
    <% end %>
  </div>
</div>

app/views/users/likes.html.erb
<div class="main user-show">
  <div class="container">
     <div class="user">
    <h2><%= @user.name %></h2>
     <% if @user.image_name? %>
      <%= image_tag @user.image_name.url %>
     <% else %>
      <%= image_tag "/user_images/default_user.jpg", class: 'user_sized' %>
     <% end %>
      <p><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
      <%= link_to("編集","/users/#{@user.id}/edit") %>
      <%= link_to("削除","/users/#{@user.id}", {method: "delete"}) %>
      <% end %>
    </div>
    
    <div class="figure-sum-posts">
      <p>投稿数合計<%= @user.posts.count %>冊</p>
    </div>
    
     <ul class="user-tabs">
      <li><%= link_to("投稿","/users/#{@user.id}") %></li>
      <li class="active"><%= link_to("いいね！","/users/#{@user.id}/likes") %></li> 
      <li><%= link_to("私のアクションプラン","/users/#{@user.id}/actionplan") %></li>
      <li><%= link_to "フォロー", follows_user_path(@user.id) %></li>
      <li><%= link_to "フォロワー", followers_user_path(@user.id) %></li>
    </ul>
    
     <% @likes.each do |like| %>
     
      <% post = Post.find_by(id: like.post_id) %>
      
      <div class="posts-index-item">
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to(post.user.name, "/users/#{post.user.id}") %>
          </div>
          <%= link_to(post.content, "/posts/#{post.id}") %>
        </div>
      </div>
    
    <% end %>
    
  </div>
</div>

app/views/users/login_form.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">ログイン</div>
    <div class="form users-form">
      <div class="form-body">
        <% if @error_message %>
          <div class="form-error">
            <%= @error_message %>
          </div>
        <% end %>
        
        <%= form_tag("/login") do %>
        <p>メールアドレス</p>
        <input name="email" value="<%= @email %>">
        <p>パスワード</p>
        <input name="password" type="password" value="<%= @password %>">
        <input type="submit" value="ログイン">
        <% end %>
        
        
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">新規ユーザー登録</div>
    <div class="form users-form">
      <div class="form-body">
        <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
        
        
        <%= form_tag("/users") do %>
          <p>ユーザー名</p>
          <input name="name" value="<%= @user.name %>">
          <p>メールアドレス</p>
          <input name="email" value="<%= @user.email %>">
          <p>パスワード</p>
          <input name="password" type="password" value="<%= @user.password %>">
          <input type="submit" value="新規登録">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <img src="<%="/user_images/#{@user.image_name}" %>" alt="サンプル" width="100" height="100">
      <h2><%= @user.name %></h2>
      <p><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
      <%= link_to("編集","/users/#{@user.id}/edit") %>
      <%= link_to("削除","/users/#{@user.id}/destroy", {method: "post"}) %>
      <% end %>
    </div>
    
    <div class="figure-sum-posts">
      <p>投稿数合計<%= @user.posts.count %>冊</p>
    </div>
   
    
    <ul class="user-tabs">
      <li class="active"><%= link_to("投稿","/users/#{@user.id}") %></li>
      <li><%= link_to("いいね！","/users/#{@user.id}/likes") %></li> 
      <li><%= link_to("私のアクションプラン","/users/#{@user.id}/actionplan") %></li>
    </ul>
   
      
    <% @user.posts.each do |post| %>
    <div class="posts-index-item">
      <div class="post-right">
        <div class="post-user-name">
          <%= link_to(post.user.name, "/users/#{post.user.id}") %>
        </div>
        <%= link_to(post.content,"/posts/#{post.id}") %>
      </div>
    </div>
    <% end %>
    
  </div>
</div>