config/routes.rb
Rails.application.routes.draw do
  
  get '/login', to: 'users#login_form'
  post '/login', to: 'users#login'
  post '/logout', to: 'users#logout'
  
  get '/users/:id/likes', to: 'users#likes'
  get '/users/:id/actionplan', to: 'users#actionplan'
  
  resources :users do
    resources :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  root 'static_pages#home'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :points, dependent: :destroy
  accepts_nested_attributes_for :points, allow_destroy: true
  
  mount_uploader :post_image, PostImageUploader
  mount_uploader :post_document_image, PostDocumentImageUploader
  validates :content, presence: true
  validates :content2, presence: true
  validates :user_id, presence: true
  
  def user
    return User.find_by(id: self.user_id)
  end
  
  def self.search(search)
    if search
      Post.where('content LIKE ?',"%#{search}%")
    else
      Post.all
    end
  end
  
 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user
  before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}
  
  def ensure_correct_user
    @post = Post.find_by(id: params[:id])
    if @post.user_id != @current_user.id
      flash[:notice] = "権限がありません"
      redirect_to("/posts")
    end
  end
  
  
  
  def index
    @posts = Post.all.paginate(page: params[:page],per_page:5).order(created_at: :desc).search(params[:search]).includes(:user)
  end
  
  
  def new
    @post = Post.new
    @post.points.build
  end
  
  def show
    @user = @post.user
    @comment = Comment.find_by(id: params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:post)
    @points = @post.points
  end
  
  
  def create
    @post = Post.new(post_params)
    @post.user_id = @current_user.id
    if @post.save
     flash[:notice] = "投稿を作成しました"
     redirect_to posts_url
    else
     flash[:notice] = "「タイトル」と「一言要約」を入力してください"
     render :new
    end
  end
    
  
  def edit
  end
  
  def update
   if @post.update(post_params)
    flash[:notice] = "投稿を更新しました"
    redirect_to("/posts/#{@post.id}")
   else
    flash[:notice] = "「タイトル」と「一言要約」を入力してください"
     redirect_to("/posts/#{@post.id}/edit")
   end
  end
  
  def destroy
    @post.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to posts_url
  end
  
  private
  
  def set_post
    @post = Post.find_by(id: params[:id])
  end
  
  def post_params
    params.require(:post).permit(:content, :content2, :review, :actionplan, :post_image, :post_document_image,:points_attributes=>[:id, :post_id, :content6, :_destroy])
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">編集する</h1>
   <%= nested_form_for @post do |f| %>
    <div class="form">
      <div class="form-body">
        <h3>タイトル</h3>
        <%= f.text_field :content, class: 'form-control' %><br>
        <br>
        <div class="post-image-form">
            <h3>表紙画像</h3>
            <%= f.file_field :post_image %>
        </div>
        <br>
        
        <h3>一言要約</h3>
        <%= f.text_field :content2, class: 'form-control' %>
        <br>
        <br>
         
         <div class="point-heading">
            <h2><要点整理></h2>
         </div>
         
       
         <!--Create Point-->
             <h3>Point</h3>
             <%= f.fields_for :points do |f| %>
                 <%= f.text_area :content6, class: 'form-control' %>
                 <%= f.link_to_remove "Delete Point" %>
             <% end %>
                 <%= f.link_to_add "Create Point", :points, class: 'btn btn-primary'%>
         
         <br>
         <div class="post-image-form">
            <h3>図、ドキュメントなど</h3>
            <%= f.file_field :post_document_image, class: 'form-control' %>
        </div>
         <br>
         <h3>レビュー</h3>
         <%= f.text_area :review, class: 'form-control' %>
         <br>
         <h3>私のアクションプラン</h3>
         <%= f.text_area :actionplan, class: 'form-control' %>
         
          
        <%= f.submit '保存する', class: 'btn btn-primary' %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main posts-index">
  <div class="container">
      
      <!-- 検索拡張機能 -->
    <p>検索</p>
      <%= form_tag("/posts", method: :get) do %>
          <%= text_field_tag :search, params[:search] %><br>
          <%= submit_tag 'Search', :name => nil %>
      <% end %>
      
     <%= will_paginate @posts, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>
      <% @posts.each do |post| %>
        <div class="posts-index-item">
            
       
            <div class="post-left">
              <% if post.user.image_name? %>
               <%= image_tag post.user.image_name.url %>
              <% else %>
               <%= image_tag "/user_images/default_user.jpg" %>
              <% end %>
              <div class="post-user-name-index">
              <%= link_to(post.user.name,"/users/#{post.user.id}") %><br>
            </div>
          </div>
          
          <div class="post-right">
            
           
        
            
          
           <div class="title-container">
             
            
               <p>表紙画像</p>
               <% if post.post_image? %>
                <%= image_tag post.post_image.url %>
               <% else %>
                <%= image_tag "/post_images/default_post.jpg", class: 'sized' %>
               <% end %>
             
             
             <h2>タイトル</h2>
            <div class="book-title-index">
              <%= link_to(post.content, "/posts/#{post.id}") %><br>
            </div>
           </div>
              
            <div class="heading-container">
               <h3>一言要約</h3>
              <div class="book-heading-index">
               <%= post.content2 %>
              </div>
            </div>
             
          </div>
        </div>
      <% end %>
     <%= will_paginate @posts, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">投稿する</h1>
    <%= nested_form_for @post do |f| %>
    <div class="form">
      <div class="form-body">
        <h3>タイトル</h3>
        <%= f.text_field :content, class: 'form-control' %>
        <br>
        <div class="post-image-form">
            <h3>表紙画像</h3>
            <%= f.file_field :post_image %>
        </div>
        <br>
        
        <h3>一言要約</h3>
        <%= f.text_field :content2, class: 'form-control' %>
        <br>
        <br>
         
         <div class="point-heading">
            <h2><要点整理></h2>
         </div>
         
       
         <!--Create Point-->
             <h3>Point</h3>
             <%= f.fields_for :points do |f| %>
                 <%= f.text_area :content6, class: 'form-control' %>
                 <%= f.link_to_remove "Delete Point" %>
             <% end %>
                 <%= f.link_to_add "Create Point", :points, class: 'btn btn-primary'%>
         
         <br>
         <div class="post-image-form">
            <h3>図、ドキュメントなど</h3>
            <%= f.file_field :post_document_image %>
        </div>
        <br>
         <h3>レビュー</h3>
         <%= f.text_area :review, class: 'form-control' %>
         <br>
         <h3>私のアクションプラン</h3>
         <%= f.text_area :actionplan, class: 'form-control' %>
         <br>
          
        <%= f.submit '投稿する', class: 'btn btn-primary' %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container">
    <div class="posts-show-item">
      
       <div class="post-left">
        <% if @post.user.image_name? %>
         <%= image_tag @post.user.image_name.url %>
        <% else %>
         <%= image_tag "/user_images/default_user.jpg" %>
        <% end %>
        <div class="post-user-name-index">
            <%= link_to(@post.user.name,"/users/#{@post.user.id}") %><br>
        </div>
        </div>
      
    <div class="title-container">
      <h1>タイトル</h1>
     <div class="book-title-show">
          『<%= @post.content %>』<br>
     </div>
    </div>
    
    
        <p>表紙画像</p>
        <% if @post.post_image? %>
          <%= image_tag @post.post_image.url %>
        <% else %>
          <%= image_tag "/post_images/default_post.jpg", class: 'sized' %>
        <% end %>
    
         
    <div class="heading-container">
      <h2>一言要約</h2>
     <div class="book-heading-show">
        <%= @post.content2 %>
     </div>
    </div>
     
    <div class="heading-container-point">
     
    
    <% @post.points.each.with_index(1) do |point, i| %>
        <h3>Point<%= i %></h3>
        <%= simple_format(point.content6) %>
    <% end %>
    
    <div class="post-image">
        <h3>図、ドキュメントなど</h3>
        <% if @post.post_document_image? %>
          <%= image_tag @post.post_document_image.url %>
        <% else %>
          <%= "図、ドキュメントなどは空白です。" %>
        <% end %>
    </div>
    
    <div class="heading-container-point">
        <h3>レビュー</h3>
     <div class="book-point-show">
        <%= simple_format(@post.review) %>
     </div>
    </div>
    
    <div class="heading-container-point">
        <h3>私のアクションプラン</h3>
     <div class="book-point-show">
        <%= simple_format(@post.actionplan) %>
     </div>
    </div>
     
     <div class="like_button">
         <%= render partial: 'likes/like', locals: { post: @post } %>
     </div>
     
      <div class="post-time">
        <%= @post.created_at %>
      </div>
      
      <%= form_with(model: [@post, @comment], local: true) do |f| %>
          <%= f.text_area :text, class: 'form-control' %>
          <br>
          <br>
          <%= f.submit "コメントする", class: "btn btn-primary" %>
      <% end %>
      
     </div>
     
     
      <% @comments.each do |comment| %>
      <div class="posts-show-item">
      <p>コメント</p>
      <div class="post-left">
        <% if comment.user.image_name? %>
         <%= image_tag comment.user.image_name.url %>
        <% else %>
         <%= image_tag "/user_images/default_user.jpg" %>
        <% end %>
            <div class="post-user-name-index">
              <%= link_to(comment.user.name,"/users/#{comment.user_id}") %><br>
            </div>
      </div>
      <%= comment.text %>
      <br>
      <br>
      <% if comment.user_id == @current_user.id %>
        <%= link_to "コメント削除", post_comment_path(@post, comment), method: :delete %>
      <% end %>
      </div>
      <% end %>
  
      <% if @post.user_id == @current_user.id %>
      <div class="post-menus">
        <%= link_to("編集", edit_post_path) %>
        <%= link_to("削除", post_path, {method: "delete"}) %>
      </div>
      <% end %>
      
      
    </div>
  </div>
</div>